ekf_localization:
  frequency: 50
  odom0: odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true, true, false,
                 false, false, false,
                 false, false, false]
  odom0_differential: false

  imu0: imu/data_compass
  imu0_config: [false, false, false,
                false, false, true,
                false, false, false,
                false, false, true,
                false, false, false]
  imu0_differential: false 
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

