ekf_localization:
  frequency: 50
  odom0: odom
  two_d_mode: true
  odom0_config: [true, true, false,
                 false, false, true,
                 true, true, false,
                 false, false, true,
                 false, false, false]
  odom0_differential: false

# imu0: imu/data_compass
#  imu0_config: [false, false, false,
#                true, true, true,
#                false, false, false,
#                true, true, true,
#                false, false, false]
#  imu0_differential: true #fusing absolute position or orientation data should be done differentially-->
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

